# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DataFlux.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def __init__(self):
        self.comboBox = QtWidgets.QComboBox()  # 初始化 comboBox

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(938, 551)
        Dialog.setStyleSheet("QDialog\n"
                             "{\n"
                             "background-color: #5B5B5B;\n"
                             "}")
        Dialog.setSizeGripEnabled(False)
        Dialog.setModal(False)

        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 70, 351, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setStyleSheet("#pushButton{\n"
                                      "background-color: #FF8000;\n"
                                      "}")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)

        self.label_status = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_status.setStyleSheet("color: white;")
        self.label_status.setObjectName("label_status")
        self.horizontalLayout.addWidget(self.label_status)

        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 30, 291, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")

        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label.setStyleSheet("#label, #label_2{\n"
                                 "color:white;\n"
                                 "}")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)

        spacerItem1 = QtWidgets.QSpacerItem(178, 36, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)

        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_2.setStyleSheet("color:white;")
        self.label_2.setObjectName("label_2")

        # 使用 self.comboBox
        self.horizontalLayout_2.addWidget(self.comboBox)

        self.retranslateUi(Dialog)
        self.pushButton.clicked.connect(self.handle_upload_button_click)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "上傳資料csv"))
        self.label_status.setText(_translate("Dialog", "請選擇上傳檔案"))
        self.comboBox.addItem(_translate("Dialog", "模型1"))
        self.comboBox.addItem(_translate("Dialog", "模型2"))
        self.comboBox.addItem(_translate("Dialog", "模型3"))
        self.label.setText(_translate("Dialog", "pyqt_法國我"))
        self.label_2.setText(_translate("Dialog", "機器學習模型選擇"))

    def handle_upload_button_click(self):
        options = QtWidgets.QFileDialog.Options()
        file_path, _ = QtWidgets.QFileDialog.getOpenFileName(None, "選擇 CSV 文件", "", "CSV Files (*.csv);;All Files (*)", options=options)

        if file_path:
            self.label_status.setText(f"已選擇檔案：{file_path}")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())