# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DataFlux2.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from controller2 import Controller2 

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(938, 551)
        Dialog.setStyleSheet("QDialog\n"
"{\n"
"background-color: #5B5B5B;\n"
"}\n"
"\n"
"QLabel\n"
"{\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton , QComboBox\n"
"{\n"
"\n"
"background-color:  #FF8000;\n"
"\n"
"}")
        Dialog.setSizeGripEnabled(False)
        Dialog.setModal(False)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 60, 461, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.csv_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.csv_button.setStyleSheet("")
        self.csv_button.setDefault(False)
        self.csv_button.setObjectName("csv_button")
        self.horizontalLayout.addWidget(self.csv_button)
        spacerItem = QtWidgets.QSpacerItem(28, 26, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.csv_path = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.csv_path.setStyleSheet("")
        self.csv_path.setObjectName("csv_path")
        self.horizontalLayout.addWidget(self.csv_path)
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(20, 150, 201, 21))
        self.comboBox.setStyleSheet("")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 96, 39))
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 20, 289, 39))
        self.label.setStyleSheet("")
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        self.controller2 = Controller2(self)
        self.csv_button.clicked.connect(self.controller2.handle_upload_button_click) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.csv_button.setText(_translate("Dialog", "上傳資料csv"))
        self.csv_path.setText(_translate("Dialog", "請上傳檔案"))
        self.comboBox.setItemText(0, _translate("Dialog", "模型1"))
        self.comboBox.setItemText(1, _translate("Dialog", "模型2"))
        self.comboBox.setItemText(2, _translate("Dialog", "模型3"))
        self.label_2.setText(_translate("Dialog", "機器學習模型選擇"))
        self.label.setText(_translate("Dialog", "pyqt_法國我"))
# import qt_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
