# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DataFlux2.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QApplication, QDialog, QStackedWidget, QVBoxLayout, QComboBox, QLineEdit
from controller2 import Controller2 

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(938, 551)
        Dialog.setStyleSheet("QDialog\n"
"{\n"
"background-color: #5B5B5B;\n"
"}\n"
"\n"
"QLabel\n"
"{\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton , QComboBox\n"
"{\n"
"\n"
"background-color:  #FF8000;\n"
"\n"
"}")
        Dialog.setSizeGripEnabled(False)
        Dialog.setModal(False)
        
        # 左上區域
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 60, 461, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.csv_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.csv_button.setStyleSheet("")
        self.csv_button.setDefault(False)
        self.csv_button.setObjectName("csv_button")
        self.horizontalLayout.addWidget(self.csv_button)
        spacerItem = QtWidgets.QSpacerItem(28, 26, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.csv_path = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.csv_path.setStyleSheet("")
        self.csv_path.setObjectName("csv_path")
        self.horizontalLayout.addWidget(self.csv_path)
        
        # 右上區域
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.stackedWidget = QStackedWidget()
        
        # 頁面1
        self.page1 = QtWidgets.QWidget()
        self.page1Layout = QVBoxLayout(self.page1)
        self.page1Layout.addWidget(QLineEdit("Page 1 Option"))
        self.stackedWidget.addWidget(self.page1)
        
        # 頁面2，這裡可以添加其他頁面
        # self.page2 = QWidget()
        # self.page2Layout = QVBoxLayout(self.page2)
        # self.page2Layout.addWidget(QLineEdit("Page 2 Option"))
        # self.stackedWidget.addWidget(self.page2)
        
        self.comboBox.setGeometry(QtCore.QRect(20, 150, 201, 21))
        self.comboBox.setStyleSheet("")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("Kmeans")
        self.comboBox.addItem("模型2")
        self.comboBox.addItem("模型3")
        
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 96, 39))
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 20, 289, 39))
        self.label.setStyleSheet("")
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        
        # 創建 Controller2 的實例
        self.controller2_obj = Controller2(self)
        # 連接按鈕點擊事件到 Controller2 的槽函數
        self.csv_button.clicked.connect(self.controller2_obj.handle_upload_button_click)
        # 連接 QComboBox 的 currentIndexChanged 信號到 Controller2 的槽函數
        self.comboBox.currentIndexChanged.connect(self.controller2_obj.handle_combobox_changed)
        
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.csv_button.setText(_translate("Dialog", "上傳資料csv"))
        self.csv_path.setText(_translate("Dialog", "請上傳檔案"))
        self.label_2.setText(_translate("Dialog", "機器學習模型選擇"))
        self.label.setText(_translate("Dialog", "pyqt_法國我"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog() # 建立 QDialog 的實例，創建主窗口
    ui = Ui_Dialog() # 實例化 UI 對象，
    ui.setupUi(Dialog) # 設置 UI 對象
    Dialog.show()
    sys.exit(app.exec_())

